security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        in_database:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: in_database
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: /profil
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: produit

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profil, roles: ROLE_USER }
        - { path: ^/produit/add, roles: ROLE_USER }
        - { path: ^/produit/edit, roles: ROLE_USER }
    access_denied_url: /produit
