easy_admin:
  entities:
    Contact:
      class: App\Entity\Contact
      list:
        fields:
          - {property: 'id'}
          - {property: 'nom'}
          - {property: 'prenom', label: "Prénom"}
          - {property: 'email'}
          - {property: 'createdAt', label: "Date d'ajout", format: "d/m/Y à H:m:s"}
          - {property: 'contenu'}

        actions:
            - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary mb-1'}
            - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}

      form:
        fields:
          - {property: 'nom'}
          - {property: 'prenom'}
          - {property: 'email'}
          - {property: 'createdAt', label: "Date d'ajout"}
          - {property: 'contenu'}