easy_admin:
  entities:
    User:
      class: App\Entity\User
      list:
        fields:
          - {property: 'id'}
          - {property: 'username', label: "Pseudo"}
          - {property: 'roles'}
          - {property: 'email'}

        actions:
            - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary mb-1'}
            - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}

      form:
        fields:
          - {property: 'username', label: "Pseudo"}
          - {property: 'roles', type: 'collection'}
          - {property: 'email'}